import type { EventWithDetails, City, Tag } from "./types"

export const MOCK_CITIES: City[] = [
  {
    id: "1",
    name: "New York",
    state: "NY",
    country: "US",
    slug: "new-york",
    is_active: true,
    latitude: 40.7128,
    longitude: -74.006,
    timezone: "America/New_York",
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Los Angeles",
    state: "CA",
    country: "US",
    slug: "los-angeles",
    is_active: true,
    latitude: 34.0522,
    longitude: -118.2437,
    timezone: "America/Los_Angeles",
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Chicago",
    state: "IL",
    country: "US",
    slug: "chicago",
    is_active: true,
    latitude: 41.8781,
    longitude: -87.6298,
    timezone: "America/Chicago",
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "San Francisco",
    state: "CA",
    country: "US",
    slug: "san-francisco",
    is_active: true,
    latitude: 37.7749,
    longitude: -122.4194,
    timezone: "America/Los_Angeles",
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Austin",
    state: "TX",
    country: "US",
    slug: "austin",
    is_active: true,
    latitude: 30.2672,
    longitude: -97.7431,
    timezone: "America/Chicago",
    created_at: new Date().toISOString(),
  },
]

export const MOCK_TAGS: Tag[] = [
  {
    id: "t1",
    name: "Free",
    slug: "free",
    color: "#16a34a",
    category: "cost",
    is_system: true,
    created_at: "",
  },
  {
    id: "t2",
    name: "Outdoor",
    slug: "outdoor",
    color: "#15803d",
    category: "location",
    is_system: true,
    created_at: "",
  },
  {
    id: "t3",
    name: "Indoor",
    slug: "indoor",
    color: "#0369a1",
    category: "location",
    is_system: true,
    created_at: "",
  },
  {
    id: "t4",
    name: "Toddler-Friendly",
    slug: "toddler-friendly",
    color: "#d97706",
    category: "age",
    is_system: true,
    created_at: "",
  },
  {
    id: "t5",
    name: "Baby-Friendly",
    slug: "baby-friendly",
    color: "#f59e0b",
    category: "age",
    is_system: true,
    created_at: "",
  },
  {
    id: "t6",
    name: "Weekend",
    slug: "weekend",
    color: "#db2777",
    category: "time",
    is_system: true,
    created_at: "",
  },
  {
    id: "t7",
    name: "Educational",
    slug: "educational",
    color: "#0284c7",
    category: "theme",
    is_system: true,
    created_at: "",
  },
  {
    id: "t8",
    name: "Arts & Crafts",
    slug: "arts-crafts",
    color: "#c026d3",
    category: "activity",
    is_system: true,
    created_at: "",
  },
  {
    id: "t9",
    name: "Music",
    slug: "music",
    color: "#ea580c",
    category: "activity",
    is_system: true,
    created_at: "",
  },
  {
    id: "t10",
    name: "Sensory-Friendly",
    slug: "sensory-friendly",
    color: "#0891b2",
    category: "theme",
    is_system: true,
    created_at: "",
  },
  {
    id: "t11",
    name: "Nature",
    slug: "nature",
    color: "#15803d",
    category: "theme",
    is_system: true,
    created_at: "",
  },
  {
    id: "t12",
    name: "Storytime",
    slug: "storytime",
    color: "#65a30d",
    category: "activity",
    is_system: true,
    created_at: "",
  },
]

function makeDate(daysFromNow: number, hour = 10) {
  const d = new Date()
  d.setDate(d.getDate() + daysFromNow)
  d.setHours(hour, 0, 0, 0)
  return d.toISOString()
}

export const MOCK_EVENTS: EventWithDetails[] = [
  {
    id: "e1",
    title: "Musical Storytime & Singalong",
    description:
      "Join us for a sensory-rich morning of melodies, rhythm, and interactive tales. Our Musical Storytime combines the joy of reading with musical play, designed specifically for the developmental needs of toddlers. Led by professional children's entertainer, the session includes rhythmic instrument play, bubble catching, and a cozy puppet-led narrative that encourages early literacy and social bonding.",
    start_datetime: makeDate(0, 10),
    end_datetime: makeDate(0, 11),
    timezone: "America/New_York",
    venue_name: "The Sunny Nook Community Studio",
    address: "42 Maple Avenue, Brooklyn",
    city_id: "1",
    latitude: 40.6782,
    longitude: -73.9442,
    age_min: 1,
    age_max: 4,
    price: 15,
    is_free: false,
    source_url: null,
    source_name: "Community Events",
    source_id: null,
    images: ["https://picsum.photos/seed/storytime/600/400"],
    status: "published",
    ai_confidence: 0.95,
    ai_tag_provider: "openai",
    recurrence_info: null,
    is_featured: true,
    view_count: 142,
    search_vector: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    city: MOCK_CITIES[0],
    tags: [
      {
        event_id: "e1",
        tag_id: "t4",
        confidence: 0.9,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[3],
      },
      {
        event_id: "e1",
        tag_id: "t9",
        confidence: 0.95,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[8],
      },
      {
        event_id: "e1",
        tag_id: "t3",
        confidence: 0.8,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[2],
      },
    ],
    avg_rating: 4.9,
    rating_count: 24,
    is_favorited: false,
    is_in_calendar: false,
  },
  {
    id: "e2",
    title: "Sensory Storytime & Bubbles",
    description:
      "A magical hour of interactive reading, sensory bins, and the famous 'Giant Bubble Dance Party'. Perfect for active toddlers who love to move and explore.",
    start_datetime: makeDate(0, 10),
    end_datetime: makeDate(0, 11),
    timezone: "America/New_York",
    venue_name: "Little Explorers Studio",
    address: "89 Park Ave, Manhattan",
    city_id: "1",
    latitude: 40.7589,
    longitude: -73.9851,
    age_min: 2,
    age_max: 4,
    price: 15,
    is_free: false,
    source_url: null,
    source_name: null,
    source_id: null,
    images: ["https://picsum.photos/seed/bubbles/600/400"],
    status: "published",
    ai_confidence: 0.88,
    ai_tag_provider: "openai",
    recurrence_info: null,
    is_featured: false,
    view_count: 89,
    search_vector: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    city: MOCK_CITIES[0],
    tags: [
      {
        event_id: "e2",
        tag_id: "t4",
        confidence: 0.9,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[3],
      },
      {
        event_id: "e2",
        tag_id: "t10",
        confidence: 0.85,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[9],
      },
    ],
    avg_rating: 4.7,
    rating_count: 18,
    is_favorited: true,
    is_in_calendar: true,
  },
  {
    id: "e3",
    title: "Tiny Explorers: Butterfly Garden Tour",
    description:
      "An interactive walk through the city botanical garden's famous butterfly enclosure. Children will learn about metamorphosis, plant life cycles, and get up-close with hundreds of live butterflies.",
    start_datetime: makeDate(1, 9),
    end_datetime: makeDate(1, 11),
    timezone: "America/New_York",
    venue_name: "City Botanical Garden",
    address: "Bronx Park, Bronx",
    city_id: "1",
    latitude: 40.8552,
    longitude: -73.8794,
    age_min: 2,
    age_max: 6,
    price: 15,
    is_free: false,
    source_url: null,
    source_name: null,
    source_id: null,
    images: ["https://picsum.photos/seed/butterfly/600/400"],
    status: "published",
    ai_confidence: 0.92,
    ai_tag_provider: "openai",
    recurrence_info: null,
    is_featured: false,
    view_count: 203,
    search_vector: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    city: MOCK_CITIES[0],
    tags: [
      {
        event_id: "e3",
        tag_id: "t11",
        confidence: 0.95,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[10],
      },
      {
        event_id: "e3",
        tag_id: "t7",
        confidence: 0.9,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[6],
      },
      {
        event_id: "e3",
        tag_id: "t2",
        confidence: 0.8,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[1],
      },
    ],
    avg_rating: 4.8,
    rating_count: 31,
    is_favorited: false,
    is_in_calendar: false,
  },
  {
    id: "e4",
    title: "Puppet Tales & Morning Cocoa",
    description:
      "Classic stories brought to life through expert puppetry. Sip warm cocoa while the little ones are enchanted by our resident storytellers.",
    start_datetime: makeDate(1, 10),
    end_datetime: makeDate(1, 11),
    timezone: "America/New_York",
    venue_name: "The Cozy Corner Cafe",
    address: "112 Bedford Ave, Williamsburg",
    city_id: "1",
    latitude: 40.7157,
    longitude: -73.9572,
    age_min: 1,
    age_max: 3,
    price: 0,
    is_free: true,
    source_url: null,
    source_name: null,
    source_id: null,
    images: ["https://picsum.photos/seed/puppet/600/400"],
    status: "published",
    ai_confidence: 0.91,
    ai_tag_provider: "openai",
    recurrence_info: null,
    is_featured: false,
    view_count: 67,
    search_vector: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    city: MOCK_CITIES[0],
    tags: [
      {
        event_id: "e4",
        tag_id: "t12",
        confidence: 0.95,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[11],
      },
      {
        event_id: "e4",
        tag_id: "t5",
        confidence: 0.88,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[4],
      },
      {
        event_id: "e4",
        tag_id: "t1",
        confidence: 1.0,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[0],
      },
    ],
    avg_rating: 4.6,
    rating_count: 12,
    is_favorited: false,
    is_in_calendar: false,
  },
  {
    id: "e5",
    title: "Tots Yoga & Flow",
    description:
      "A gentle introduction to movement and breath for curious crawlers and walkers. Bring your mat, bring your little one, and find stillness together.",
    start_datetime: makeDate(0, 11),
    end_datetime: makeDate(0, 12),
    timezone: "America/New_York",
    venue_name: "Sunlight Studio",
    address: "55 Spring St, SoHo",
    city_id: "1",
    latitude: 40.7248,
    longitude: -73.9977,
    age_min: 0,
    age_max: 2,
    price: 15,
    is_free: false,
    source_url: null,
    source_name: null,
    source_id: null,
    images: ["https://picsum.photos/seed/yoga/600/400"],
    status: "published",
    ai_confidence: 0.87,
    ai_tag_provider: "openai",
    recurrence_info: null,
    is_featured: false,
    view_count: 55,
    search_vector: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    city: MOCK_CITIES[0],
    tags: [
      {
        event_id: "e5",
        tag_id: "t5",
        confidence: 0.92,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[4],
      },
      {
        event_id: "e5",
        tag_id: "t3",
        confidence: 0.9,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[2],
      },
    ],
    avg_rating: 4.5,
    rating_count: 9,
    is_favorited: false,
    is_in_calendar: false,
  },
  {
    id: "e6",
    title: "Messy Masterpieces",
    description:
      "Get messy! Finger painting and sensory exploration in the fresh air. Dress for a mess. All materials provided.",
    start_datetime: makeDate(0, 13),
    end_datetime: makeDate(0, 14),
    timezone: "America/New_York",
    venue_name: "Central Park West Lawn",
    address: "Central Park, Manhattan",
    city_id: "1",
    latitude: 40.7831,
    longitude: -73.9712,
    age_min: 2,
    age_max: 6,
    price: 0,
    is_free: true,
    source_url: null,
    source_name: null,
    source_id: null,
    images: ["https://picsum.photos/seed/painting/600/400"],
    status: "published",
    ai_confidence: 0.93,
    ai_tag_provider: "openai",
    recurrence_info: null,
    is_featured: true,
    view_count: 178,
    search_vector: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    city: MOCK_CITIES[0],
    tags: [
      {
        event_id: "e6",
        tag_id: "t8",
        confidence: 0.95,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[7],
      },
      {
        event_id: "e6",
        tag_id: "t2",
        confidence: 0.9,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[1],
      },
      {
        event_id: "e6",
        tag_id: "t1",
        confidence: 1.0,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[0],
      },
    ],
    avg_rating: 4.8,
    rating_count: 45,
    is_favorited: false,
    is_in_calendar: false,
  },
  {
    id: "e7",
    title: "Little Hands Pottery",
    description:
      "Children learn to shape clay with their own hands in this guided pottery workshop. Each child creates and takes home their own piece after glazing.",
    start_datetime: makeDate(1, 14),
    end_datetime: makeDate(1, 16),
    timezone: "America/New_York",
    venue_name: "Clay & Co Studio",
    address: "34 Wythe Ave, Brooklyn",
    city_id: "1",
    latitude: 40.7195,
    longitude: -73.9567,
    age_min: 3,
    age_max: 10,
    price: 20,
    is_free: false,
    source_url: null,
    source_name: null,
    source_id: null,
    images: ["https://picsum.photos/seed/pottery/600/400"],
    status: "published",
    ai_confidence: 0.89,
    ai_tag_provider: "openai",
    recurrence_info: null,
    is_featured: false,
    view_count: 91,
    search_vector: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    city: MOCK_CITIES[0],
    tags: [
      {
        event_id: "e7",
        tag_id: "t8",
        confidence: 0.93,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[7],
      },
      {
        event_id: "e7",
        tag_id: "t3",
        confidence: 0.85,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[2],
      },
    ],
    avg_rating: 4.6,
    rating_count: 15,
    is_favorited: false,
    is_in_calendar: false,
  },
  {
    id: "e8",
    title: "Nature Tot Scavenger Hunt",
    description:
      "Join us in Willow Creek Park for a guided exploration of leaves, bugs, and feathers. Kids get a discovery journal and magnifying glass to keep!",
    start_datetime: makeDate(5, 10),
    end_datetime: makeDate(5, 12),
    timezone: "America/New_York",
    venue_name: "Willow Creek Park",
    address: "Willow Creek Park, Queens",
    city_id: "1",
    latitude: 40.7282,
    longitude: -73.7949,
    age_min: 3,
    age_max: 8,
    price: 12,
    is_free: false,
    source_url: null,
    source_name: null,
    source_id: null,
    images: ["https://picsum.photos/seed/nature/600/400"],
    status: "published",
    ai_confidence: 0.94,
    ai_tag_provider: "openai",
    recurrence_info: null,
    is_featured: false,
    view_count: 63,
    search_vector: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    city: MOCK_CITIES[0],
    tags: [
      {
        event_id: "e8",
        tag_id: "t11",
        confidence: 0.95,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[10],
      },
      {
        event_id: "e8",
        tag_id: "t7",
        confidence: 0.88,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[6],
      },
      {
        event_id: "e8",
        tag_id: "t2",
        confidence: 0.92,
        is_manual_override: false,
        created_at: "",
        tag: MOCK_TAGS[1],
      },
    ],
    avg_rating: 4.7,
    rating_count: 8,
    is_favorited: false,
    is_in_calendar: false,
  },
]
