import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import path from "node:path"

const here = path.dirname(fileURLToPath(import.meta.url))

export const PKG_ROOT = path.resolve(here, "..")
export const REPO_ROOT = path.resolve(PKG_ROOT, "..", "..")
export const TOKENS_PATH = path.join(PKG_ROOT, "tokens", "tokens.json")

export function loadTokens() {
  return JSON.parse(readFileSync(TOKENS_PATH, "utf8"))
}

export const GENERATED_BANNER = `/*
 * AUTO-GENERATED by @family-events/design-system — DO NOT EDIT.
 * Source: packages/design-system/tokens/tokens.json
 * Regenerate: pnpm --filter @family-events/design-system build
 */`

export const SWIFT_BANNER = `// AUTO-GENERATED by @family-events/design-system — DO NOT EDIT.
// Source: packages/design-system/tokens/tokens.json
// Regenerate: pnpm --filter @family-events/design-system build`

export const TS_BANNER = `/* eslint-disable */
/**
 * AUTO-GENERATED by @family-events/design-system — DO NOT EDIT.
 * Source: packages/design-system/tokens/tokens.json
 * Regenerate: pnpm --filter @family-events/design-system build
 */`
