-- ============================================================================
-- M002/S01: Event embeddings infrastructure and similarity retrieval
-- ============================================================================
-- Enables pgvector, creates event_embeddings table with HNSW index, and
-- provides a find_similar_events RPC for cosine-distance similarity search.
-- ============================================================================

-- ─── Enable pgvector extension ──────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA extensions;

-- ─── event_embeddings table ─────────────────────────────────────────────────
-- Separate from events table to keep the hot table lean (~6KB per row for
-- 1536-dim float32 vectors). Supports re-embedding with different models via
-- the model column.

CREATE TABLE IF NOT EXISTS public.event_embeddings (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id   uuid NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
  embedding  extensions.vector(1536) NOT NULL,
  model      text NOT NULL DEFAULT 'text-embedding-3-small',
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT event_embeddings_event_id_unique UNIQUE (event_id)
);

COMMENT ON TABLE public.event_embeddings IS
  'Vector embeddings for event similarity search. One embedding per event, generated from title+description via OpenAI text-embedding-3-small.';
COMMENT ON COLUMN public.event_embeddings.embedding IS
  '1536-dimensional float32 vector from OpenAI text-embedding-3-small.';
COMMENT ON COLUMN public.event_embeddings.model IS
  'Embedding model identifier. Allows future model migration without schema change.';

-- ─── RLS ────────────────────────────────────────────────────────────────────
ALTER TABLE public.event_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_embeddings FORCE ROW LEVEL SECURITY;

-- Service role (edge functions) gets full access
CREATE POLICY event_embeddings_service_role_all
  ON public.event_embeddings
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- Admins can read (for dashboard inspection)
CREATE POLICY event_embeddings_admin_select
  ON public.event_embeddings
  FOR SELECT
  TO authenticated
  USING ((SELECT private.is_admin()));

GRANT SELECT ON public.event_embeddings TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.event_embeddings TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.event_embeddings_id_seq TO service_role;

-- ─── HNSW index for cosine similarity ───────────────────────────────────────
-- HNSW provides better recall than IVFFlat at our scale (< 100K events).
-- Uses cosine distance operator class (vector_cosine_ops).
-- m=16, ef_construction=64 are good defaults for < 1M rows.
CREATE INDEX IF NOT EXISTS event_embeddings_embedding_hnsw_idx
  ON public.event_embeddings
  USING hnsw (embedding extensions.vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

-- Covering index for event_id lookups (upsert, join)
CREATE INDEX IF NOT EXISTS event_embeddings_event_id_idx
  ON public.event_embeddings (event_id);

-- ─── find_similar_events RPC (private body) ─────────────────────────────────
-- Returns the top-N most similar events by cosine distance, excluding the
-- query event itself. Optional city_id filter for same-city results.
-- Cosine distance: 0 = identical, 2 = opposite. Threshold filters results.

CREATE OR REPLACE FUNCTION private.find_similar_events(
  p_embedding    extensions.vector(1536),
  p_limit        int DEFAULT 5,
  p_threshold    float DEFAULT 0.3,
  p_exclude_event_id uuid DEFAULT NULL,
  p_city_id      uuid DEFAULT NULL
)
RETURNS TABLE (
  event_id         uuid,
  title            text,
  status           public.event_status,
  cosine_distance  float,
  source_id        uuid,
  city_id          uuid
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO ''
AS $$
  SELECT
    e.id AS event_id,
    e.title,
    e.status,
    (ee.embedding OPERATOR(extensions.<=>) p_embedding)::float AS cosine_distance,
    e.source_id,
    e.city_id
  FROM public.event_embeddings ee
  JOIN public.events e ON e.id = ee.event_id
  WHERE (p_exclude_event_id IS NULL OR ee.event_id <> p_exclude_event_id)
    AND (p_city_id IS NULL OR e.city_id = p_city_id)
    AND (ee.embedding OPERATOR(extensions.<=>) p_embedding) < p_threshold
  ORDER BY ee.embedding OPERATOR(extensions.<=>) p_embedding
  LIMIT p_limit;
$$;

COMMENT ON FUNCTION private.find_similar_events IS
  'Returns top-N events most similar to the given embedding vector by cosine distance. '
  'Threshold filters out distant results (lower = more similar). '
  'Optional city_id filter restricts to same-city results.';

REVOKE EXECUTE ON FUNCTION private.find_similar_events(extensions.vector(1536), int, float, uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION private.find_similar_events(extensions.vector(1536), int, float, uuid, uuid)
  TO service_role;

-- ─── find_similar_events public wrapper (SECURITY INVOKER) ──────────────────
CREATE OR REPLACE FUNCTION public.find_similar_events(
  p_embedding    extensions.vector(1536),
  p_limit        int DEFAULT 5,
  p_threshold    float DEFAULT 0.3,
  p_exclude_event_id uuid DEFAULT NULL,
  p_city_id      uuid DEFAULT NULL
)
RETURNS TABLE (
  event_id         uuid,
  title            text,
  status           public.event_status,
  cosine_distance  float,
  source_id        uuid,
  city_id          uuid
)
LANGUAGE sql
SECURITY INVOKER
SET search_path TO ''
AS $$
  SELECT * FROM private.find_similar_events(
    p_embedding, p_limit, p_threshold, p_exclude_event_id, p_city_id
  );
$$;

REVOKE EXECUTE ON FUNCTION public.find_similar_events(extensions.vector(1536), int, float, uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.find_similar_events(extensions.vector(1536), int, float, uuid, uuid)
  TO service_role;

-- ─── Expand ai_feature_config CHECK to allow memory features ────────────────
-- Preserve existing features and add memory pipeline feature flags.

ALTER TABLE public.ai_feature_config
  DROP CONSTRAINT IF EXISTS ai_feature_config_feature_check;

ALTER TABLE public.ai_feature_config
  ADD CONSTRAINT ai_feature_config_feature_check
  CHECK (feature IN (
    'tagging', 'event-review', 'parent-tips',
    'tag-memory', 'review-memory', 'source-auto-reject'
  ));

CREATE OR REPLACE FUNCTION private.upsert_ai_feature_config(
  p_feature  text,
  p_model_id text,
  p_enabled  bool
) RETURNS void
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path = ''
AS $$
BEGIN
  IF NOT private.is_admin() THEN
    RAISE EXCEPTION 'forbidden' USING ERRCODE = '42501';
  END IF;

  IF p_feature NOT IN (
    'tagging', 'event-review', 'parent-tips',
    'tag-memory', 'review-memory', 'source-auto-reject'
  ) THEN
    RAISE EXCEPTION 'invalid feature: %', p_feature;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.approved_ai_models
    WHERE id = p_model_id
      AND is_enabled = true
  ) THEN
    RAISE EXCEPTION 'model is not approved or enabled: %', p_model_id;
  END IF;

  INSERT INTO public.ai_feature_config (feature, model_id, enabled, updated_at, updated_by)
  VALUES (p_feature, p_model_id, p_enabled, now(), auth.uid())
  ON CONFLICT (feature) DO UPDATE SET
    model_id    = EXCLUDED.model_id,
    enabled     = EXCLUDED.enabled,
    updated_at  = EXCLUDED.updated_at,
    updated_by  = EXCLUDED.updated_by;
END;
$$;

UPDATE public.ai_feature_config
SET model_id = 'gpt-5.4-nano'
WHERE feature = 'parent-tips'
  AND model_id IN ('gpt-4.1-nano', 'gpt-4.1-mini', 'gpt-4.1', 'gpt-4o', 'gpt-4o-mini');

-- Insert default feature flag rows (disabled by default — safe rollout).
-- tag-memory, review-memory, source-auto-reject don't need a model_id since
-- they use the parent feature's model. But the FK is NOT NULL, so reference
-- the current enabled low-cost model used for tagging.
INSERT INTO public.ai_feature_config (feature, model_id, enabled)
VALUES
  ('tag-memory',          'gpt-5.4-nano', false),
  ('review-memory',       'gpt-5.4-nano', false),
  ('source-auto-reject',  'gpt-5.4-nano', false)
ON CONFLICT (feature) DO NOTHING;
